apiVersion: v1
kind: Service
metadata:
  name: {{ include "flaskapp.fullname" . }}
spec:
  selector:
    app: flaskapp
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.flaskapp.service.port }}
      targetPort: {{ .Values.flaskapp.service.port }}
  type: {{ .Values.flaskapp.service.type }}
