apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysql-chart.fullname" . }}
  labels:
    app: {{ include "mysql-chart.name" . }}
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: {{ include "mysql-chart.name" . }}